theme: jekyll-theme-architect
show_downloads: false
title: Micro Frontends
description: extending the microservice paradigms to web development
github:
  is_project_page: true
  repository_url: https://github.com/neuland/micro-frontends
google_analytics: UA-84095563-2
exclude:
  - 2-composition-universal
  - 3-data-fetching
  - node_modules
